services:
  frontend:
    image: frontend
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://127.0.0.1:8080
    build:
      context: .
      dockerfile: Dockerfile_front
    container_name: frontend-app

  backend:
    image: backend
    ports:
      -  8080:8080
    environment:
      - PATH="$PATH:/usr/local/go/bin"
      - REQUEST_ORIGIN=http://127.0.0.1:5000
      - REDIS_HOST=redis
    build:
      context: .
      dockerfile: Dockerfile_back
    container_name: backend-app

  redis:
    image: redis
    container_name: redis
