services:
  simple-web-service:
    image: devopsdockeruh/simple-web-service
    ports:
      - 8080:8080
    build: .
    volumes:
      - ./text.log:/usr/src/app/text.log
    container_name: web-service-testi-webpage
    command: server -p 8080:8080
