##################################
# this is dockerfie for frontend #
##################################
FROM ubuntu:22.04

## working directory
WORKDIR /usr/src/app

## copy project to working directory
COPY material-applications/example-frontend .

## expose port 
EXPOSE 5000

## install curl and node.js
RUN apt-get update && apt-get -y install curl && \
    curl -sL https://deb.nodesource.com/setup_16.x | bash && \
    apt install -y nodejs && \
    npm install && \
    apt-get purge -y --auto-remove curl && \
    rm -rf /var/lib/apt/lists/* && \
    npm run build && \
    npm install -g serve

CMD ["sh", "-c", "serve -s -l 5000 build"]
