###################################
# this is Dockerfile for frontend #
###################################
 
## install node
FROM node:16-alpine
 
#expose port
EXPOSE 5000

## add environmental variable 1.14 exercise
ENV REACT_APP_BACKEND_URL=http://localhost:8080

## working directory
WORKDIR /usr/src/app
 
## copy project to working directory
COPY material-applications/example-frontend .
 
## build porject
RUN npm install && npm run build && npm install -g serve

CMD ["sh", "-c", "serve -s -l 5000 build"]
