services:
  frontend:
    image: frontend
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    build:
      context: .
      dockerfile: Dockerfile_front
    container_name: frontend-app
  backend:
    image: backend
    ports:
      -  8080:8080
    environment:
      - PATH="$PATH:/usr/local/go/bin"
      - REQUEST_ORIGIN=http://localhost:5000
    build:
      context: .
      dockerfile: Dockerfile_back
    container_name: backend-app
