####################################
# this is Docker file for frontend #
####################################



## install node
FROM node:16

# expose port
EXPOSE 5000


## working directory
WORKDIR /usr/src/app

## copy project to working directory
COPY material-applications/example-frontend .


## check install
RUN npm install
RUN node -v && npm -v

## add environmental variable 1.14 exercise
ENV REACT_APP_BACKEND_URL=http://localhost:8080

## build project
RUN npm run build


RUN npm install -g serve
CMD ["sh", "-c", "serve -s -l 5000 build"]
